### ISSUE TITLE
github-proxy still included in kustomize releases

### ISSUE THREAD

**Issue by loujar** [sourcegraph/deploy-sourcegraph-k8s#92]
The v5.2.0 github-proxy Deployment is still being included in the latest `deploy-sourcegraph-k8s` releases.

see https://github.com/sourcegraph/deploy-sourcegraph-k8s/tree/v5.2.7/base/sourcegraph/github-proxy

related to https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/49

**Comment by loujar** [comment]
@eseliger @jdpleiness FYI

**Comment by eseliger** [comment]
It's gone in 5.3 - is it a problem that it exists in 5.2.0? 

I think (but it's been a while) we still published these images, the container was just unused. That was purely because we didn't get to removing it in full from all deploy types before the release cut date.

**Comment by loujar** [comment]
It's not a problem beyond looking a bit messy, specifically since we no longer cut a new patch image tag for this service and have a v5.2.0 image running aside v5.2.7 images.

**Comment by eseliger** [comment]
Ah, I didn't realize we stopped tagging these images.

Do you think we should do something here, or wait for 5.3?

**Comment by loujar** [comment]
@eseliger no problem waiting until 5.3

**Comment by eseliger** [comment]
great, work done - it's not part of the deployment anymore :)
